name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      push_image:
        description: '是否推送镜像到 DockerHub？'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

      docker_tag:
        description: 'Docker 镜像标签（例如 latest、v1.0.0）'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: ${{ inputs.push_image == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and (maybe) push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ inputs.push_image == 'true' }}
          tags: gabrieliu/mediatool:${{ inputs.docker_tag }}
